### ISSUE TITLE
Getting Incorrect detections and errors

### ISSUE THREAD

**Issue by sakshamprakash01** [iitpvisionlab/LSDNet#1]
Hi,

I followed the instructions mentioned in README.md to process individual images as well as the web implementation. It results in the following errors at random-

free(): invalid pointer
python: malloc.c:4036: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

Also, plotting the predictions of 00037254.jpg in the predictions folder shows these detections-

![image](https://user-images.githubusercontent.com/32038857/199123067-adabd8bd-3fbf-47b5-98c2-cefc47182096.png)

Assuming the format of predictions [x1], [y1], [x2], [y2], [conf] refers to coordinates starting at the top-left.

Please let me know if I'm doing anything wrong.

**Comment by levTepl** [comment]
@sakshamprakash01 thanks for your feedback, I'll check it out ASAP.

**Comment by levTepl** [comment]
@sakshamprakash01 could not reproduce your error - everything works fine for me.

Could you please share the exact commands you use + environment info (OS, Docker version, etc.)?

I hope it helps.

**Comment by sakshamprakash01** [comment]
Hi @levTepl 

- My docker version is 20.10.21, 
- I'm running Ubuntu 22.04 
- with Nvidia driver version 520.61.05

Could you share your environment details as well?

Here is the sequence of steps I did-

- I already had the aforementioned nvidia drivers installed. I installed docker using the official instructions mentioned here https://docs.docker.com/engine/install/ubuntu/
- After cloning the repo,
- I ran the build_image.sh script first
- and then used detect_lines.sh script to generate predictions on images inside test_images folder
- then I used the generated prediction txt file inside the predictions folder to plot on the images using a simple script I wrote-

```
PRED_TXT = '/mnt/IPS-Drive/LSDNet/predictions/00037254.jpg.txt'
IMG_PATH = '/mnt/IPS-Drive/LSDNet/visualization/test_images/00037254.jpg'
CONF_THRESH = 0.7

img = cv.imread(IMG_PATH)

with open(PRED_TXT) as txt:
    predictions = txt.read().splitlines()
    for p in predictions:
        rec = p.split()
        if float(rec[-1]) > CONF_THRESH:
            x1 = int(float(rec[0]))
            x2 = int(float(rec[1]))
            y1 = int(float(rec[2]))
            y2 = int(float(rec[3]))
            cv.line(img, (x1,y1), (x2,y2), (0,0,255), 2)

cv.imwrite(os.path.join(os.path.dirname(__file__),os.path.basename(IMG_PATH)),img)
```

Running the 'detect_lines.sh' script multiple times yields different errors everytime but other times it runs successfully too albeit the detections dont seem to be correct.
![image](https://user-images.githubusercontent.com/32038857/199367589-888ea8cf-9d2c-4fd5-8326-7511f84401a1.png)


Additionally I also tried on another image of mine I thought I should share-
![image](https://user-images.githubusercontent.com/32038857/199367639-f8ececc2-b489-44d4-b259-9321408d3c9e.png)

I'd be highly obliged if you could help me out with this, I'm really interested in getting this up and running. I can also connect with you on a quick call if you think it might help resolve the issue faster.

**Comment by levTepl** [comment]
@sakshamprakash01 now I see it :)

# 1. Visualization

README, section "Running on Your Images", `out_path - path where predicted segments will be saved in .txt format (x1,y1,x2,y2,conf) - the coordinates of segments' endpoints and segment confidence` <- CORRECT

your code implies `x1,x2,y1,y2` <- INCORRECT
```python
            x1 = int(float(rec[0]))
            x2 = int(float(rec[1]))
            y1 = int(float(rec[2]))
            y2 = int(float(rec[3]))
```

good luck :)

# 2. free() errors

"Running the 'detect_lines.sh' script multiple times yields different errors everytime but other times it runs successfully too albeit the detections dont seem to be correct."

Looks like it fails during the destruction of smth, maybe the predictions are saved properly before the crash. Could you check it?
Unfortunately, I cant reproduce this issue.

I hope you still can test the algorithm for your needs.

**Comment by sakshamprakash01** [comment]
1. Thank you for pointing out the error, I have been able to fix that and now am getting the correct plots.

![image](https://user-images.githubusercontent.com/32038857/199639926-8720a576-ada7-461b-88ef-a62caf137459.png)

3. The random errors seem to still be coming. The 3 types that I have identified, in decreasing order of frequency are-
Error#1: `free(): invalid pointer`
Error#2: `python: malloc.c:4036: _int_malloc: Assertion (unsigned long) (size) >= (unsigned long) (nb)' failed.`
Error#3: `corrupted size vs. prev_size`

> Looks like it fails during the destruction of smth, maybe the predictions are saved properly before the crash. Could you check it?
Unfortunately, I cant reproduce this issue.

Yes I did see the predictions being saved despite the error in a few cases. 

![image](https://user-images.githubusercontent.com/32038857/199639797-690fcd02-5e8b-4029-9487-28ab4604e37e.png)

Could you please share your environment information i.e. nvidia drivers, docker version, gcc, OS etc. Maybe matching those could mitigate the issue. 

Thanks

**Comment by levTepl** [comment]
@sakshamprakash01

I've looped `detect_lines.sh` x100, no failures :(

my env, nothing special...
- Docker: `version 20.10.12, build 20.10.12-0ubuntu2~20.04.1`
- OS: `ID_LIKE=ubuntu PRETTY_NAME="Linux Mint 20.3" VERSION_ID="20.3"`

NVIDIA stuff, despite its not used in our build (intentionally, to avoid compatibility issues):
- `NVIDIA GeForce RTX 3070 Laptop GPU`
- `NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6`

I'll try to test in your environment, maybe it would help.

**Comment by sakshamprakash01** [comment]
Thank you so much @levTepl, I am hoping this was an issue of version mismatch. I shall get back to you in case a similar system doesn't work.

Closing the thread.
